//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutorXLibro
    {
        public int IDAutorXLibro { get; set; }
        public int IDAutor { get; set; }
        public int IDLibro { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Libro Libro { get; set; }
    }
}
