//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ejemplar
    {
        public Ejemplar()
        {
            this.EjemplarXPrestamo = new HashSet<EjemplarXPrestamo>();
            this.Autor = new HashSet<Autor>();
        }
    
        public int IDEjemplar { get; set; }
        public int IDCategoria { get; set; }
        public int IDGenero { get; set; }
        public int IDEditorial { get; set; }
        public int IDEstado { get; set; }
        public int IDUbicacion { get; set; }
        public Nullable<int> IDCasaDisquera { get; set; }
        public string Titulo { get; set; }
        public string Edicion { get; set; }
        public int Duracion { get; set; }
        public int Extension { get; set; }
        public Nullable<int> IDModalidad { get; set; }
        public int ISBN { get; set; }
        public int ISSN { get; set; }
    
        public virtual Casa_Disquera Casa_Disquera { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual Editorial Editorial { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Genero Genero { get; set; }
        public virtual Modalidad Modalidad { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
        public virtual ICollection<EjemplarXPrestamo> EjemplarXPrestamo { get; set; }
        public virtual ICollection<Autor> Autor { get; set; }
    }
}
