//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado
    {
        public Estado()
        {
            this.Libro = new HashSet<Libro>();
            this.Socio = new HashSet<Socio>();
            this.Prestamo = new HashSet<Prestamo>();
        }
    
        public int IDEstado { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Libro> Libro { get; set; }
        public virtual ICollection<Socio> Socio { get; set; }
        public virtual ICollection<Prestamo> Prestamo { get; set; }
    }
}
