//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        public Prestamo()
        {
            this.LibroXPrestamo = new HashSet<LibroXPrestamo>();
        }
    
        public int IDPrestamo { get; set; }
        public int IDSocio { get; set; }
        public Nullable<System.DateTime> FechaPrestamo { get; set; }
        public int IDEstado { get; set; }
    
        public virtual ICollection<LibroXPrestamo> LibroXPrestamo { get; set; }
        public virtual Socio Socio { get; set; }
        public virtual Estado Estado { get; set; }
    }
}
