//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Socio
    {
        public Socio()
        {
            this.Prestamo = new HashSet<Prestamo>();
        }
    
        public int IDSocio { get; set; }
        public int IDEstado { get; set; }
        public int IDLocalidad { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> DNI { get; set; }
        public string Domicilio { get; set; }
        public Nullable<long> Telefono { get; set; }
        public string Correo { get; set; }
        public byte[] Foto { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Localidad Localidad { get; set; }
        public virtual ICollection<Prestamo> Prestamo { get; set; }
    }
}
